apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openjdk
  template:
    metadata:
      labels:
        app: openjdk
    spec:
      containers:
        - name: openjdk-container
          image: fatimatabassum/fatima12:IMAGE_TAG
          ports:
            - containerPort: 80
